### PR TITLE
Data upload endpoints

### LINKED ISSUE #22: Add an endpoint for uploading encrypted file
- [x] Add REST-style PUT/POST handler in web-server
 - [x] Call the DataEnclaveActor with the http request body

### LINKED ISSUE #24: Save sealed data returned from the data-enclave as part of the upload pipeline
- [x] Create a library for handling the Azure Blob storage calls (and other ocalls)
 - [x] Persist data passed to the ocall and save

Use the Azure sdk for rust if available, otherwise save the file locally for now. https://github.com/Azure/azure-sdk-for-rust

The data should be persisted using a UUID generated by the enclave as the key.

### PR DESCRIPTION
**Pull request by longtomjr**
depends on: #31 

Cherry picked from 807bed887f072bab271734e22450d8d8f6314df8 and 0af7ed9769d2f488d7dce56c6e1e6d41bdc08423

### CODE REVIEW

**Comment by PiDelport** [comment]
(This PR replaces #29.)

**Comment by PiDelport** [comment]
(Rebased to follow the updates in #31.)

**Review by Nghondzweni — APPROVED** [review]

**Comment by PiDelport** [comment]
(Rebased to refresh)

**Review by PiDelport — APPROVED** [review]
Cool!

As part of making sure I understand everything, I ran through and added some lint cleanups, tweaks, and rustdocs, and added to the `data_service_data_upload_ok` test a bit.

Can you check that that all look sensible?

**Review by PiDelport — APPROVED** [review]
@longtomjr: Last round of changes done!

**Pull request merged**
