### PR TITLE
feat(rtc_types): more enclave message work for set_access_key

### PR DESCRIPTION
**Pull request by PiDelport**
This adds `set_access_key::SetAccessKeyResult`, and makes `SealingError` FFI-compatible.

Precedes PR #87

### CODE REVIEW

**Comment by PiDelport** [comment]
Note: This is actually ready for review, and doesn't actually depend on PR #104, so #104 and #105 could be reviewed and merged in any order: they're just stacked in sequence currently to ease PR #87.

**Review by longtomjr — APPROVED** [review]
Looks good. Can you just expand on the reason for renaming the C bindings (maybe add a comment in the build file)

**Review by Nghondzweni — APPROVED** [review]

**Comment by PiDelport** [comment]
(Rebased to main after merge)

**Comment by PiDelport** [comment]
@longtomjr: Good idea, yeah!

**Comment by PiDelport** [comment]
@longtomjr: I factored out the enclaves' cbindgen config, and added documentation there: f1e3c1d, 61b48f3

How does that look?

**Review by longtomjr — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
