### PR TITLE
feat(rtc_types): add enclave_messages, with set_access_key

### PR DESCRIPTION
**Pull request by PiDelport**
Supporting functionality for issue #37

Precedes PR #87

### CODE REVIEW

**Review by longtomjr — APPROVED** [review]
Looks good!

**Review by Nghondzweni — APPROVED** [review]
@PiDelport I see you refactored the `set_access_key` enclave_mesages code into the `ffi_set_access_key` module and renamed `REQUEST_SIZE` to `SET_ACCESS_KEY_REQUEST_SIZE`. Will all other enclave messages be defined this way? Also does this allow us now to define request sizes without conflicts?

**Comment by PiDelport** [comment]
@Nghondzweni: Yeah, for now, it looks like we'll have to use this approach to have both generic and non-generic versions of the types, for FFI purposes.

If / when cbindgen gets better support for creating bindings for const generic types, we'll hopefully be able to drop these, but we'll have to follow the upstream issues for that.

**Comment by PiDelport** [comment]
(Rebased to refresh.)

**Pull request merged**
